# -------------------------------------------------------------------------
# # This is a spack user-configuration file.
# #
# # Per-spack-instance settings (overrides defaults):
# #   $SPACK_ROOT/etc/spack/defaults/config.yaml
# #
# # Per-user settings (overrides default and site settings):
# #   ~/.spack/config.yaml
# # -------------------------------------------------------------------------
config:
  install_tree:
    # Your path to root of the install tree (by default: $spack/opt/spack):
    root: $HOME/my_spack_installs
    # Change how install tree will be organized (by default: "${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH}")
    projections: 
      all: "${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}"

